// البيانات الأولية التي تظهر عند فتح التطبيق أول مرة (أو بعد "استعادة البيانات النموذجية").
// التواريخ بالتقويم الميلادي. كثير من تواريخ السيرة تقريبية، وقد يختلف فيها أهل العلم،
// فعدّلها بحرية بحسب المصادر التي تعتمدها.
//
// حقول الحدث:
//   id, title, category, startYear, startMonth (1-12، اختياري),
//   endYear / endMonth (اختياري، للأحداث الممتدة),
//   approximate (true/false), location, description, sources

window.SEED_CATEGORIES = [
  { id: "life", name: "حياة النبي ﷺ", color: "#0f766e" },
  { id: "revelation", name: "الوحي والتشريع", color: "#b45309" },
  { id: "family", name: "آل البيت", color: "#be185d" },
  { id: "companions", name: "الصحابة", color: "#4338ca" },
  { id: "battles", name: "الغزوات والسرايا", color: "#b91c1c" },
  { id: "diplomacy", name: "العهود والمراسلات", color: "#7e22ce" },
  { id: "world", name: "أحداث العالم", color: "#475569" }
];

window.SEED_EVENTS = [
  // ---- حياة النبي ﷺ ----
  { id: "e1", title: "عام الفيل ومولد النبي ﷺ", category: "life", startYear: 570, startMonth: 4, approximate: true, location: "مكة",
    description: "زحف أبرهة بجيشه من اليمن ومعه الفيل لهدم الكعبة فردّه الله. ووُلد النبي محمد ﷺ في ربيع الأول من العام نفسه." },
  { id: "e2", title: "نشأته في بني سعد عند حليمة", category: "life", startYear: 570, endYear: 575, approximate: true, location: "بادية بني سعد",
    description: "استُرضع في البادية عند حليمة السعدية على عادة قريش، وفي هذه المدة كانت حادثة شق الصدر." },
  { id: "e3", title: "وفاة أمه آمنة", category: "life", startYear: 576, approximate: true, location: "الأبواء",
    description: "توفيت آمنة بنت وهب في طريق عودتها من يثرب وهو ابن ست سنين تقريبًا، فكفله جده عبد المطلب." },
  { id: "e4", title: "وفاة جده عبد المطلب", category: "life", startYear: 578, approximate: true, location: "مكة",
    description: "توفي جده وهو ابن ثماني سنين تقريبًا، فكفله عمه أبو طالب." },
  { id: "e5", title: "رحلته إلى الشام ولقاء بحيرى الراهب", category: "life", startYear: 582, approximate: true, location: "بُصرى، الشام",
    description: "خرج مع عمه أبي طالب في تجارة وهو ابن اثنتي عشرة سنة تقريبًا، فرأى فيه الراهب بحيرى علامات النبوة." },
  { id: "e6", title: "حلف الفضول", category: "diplomacy", startYear: 590, approximate: true, location: "مكة",
    description: "حلف تعاهدت فيه بطون من قريش على نصرة كل مظلوم بمكة. وقال ﷺ: لو أُدعى به في الإسلام لأجبت." },
  { id: "e7", title: "زواجه من خديجة رضي الله عنها", category: "family", startYear: 595, approximate: true, location: "مكة",
    description: "تزوج خديجة بنت خويلد، التاجرة الشريفة، بعد أن خرج في تجارتها إلى الشام، وهو ابن خمس وعشرين سنة تقريبًا." },
  { id: "e8", title: "إعادة بناء الكعبة", category: "life", startYear: 605, approximate: true, location: "مكة",
    description: "جددت قريش بناء الكعبة، واختلفوا فيمن يضع الحجر الأسود، فحكّموه ﷺ فوضعه في ثوب حملته القبائل جميعًا." },
  { id: "e9", title: "بدء الوحي في غار حراء", category: "revelation", startYear: 610, startMonth: 8, approximate: true, location: "غار حراء، جبل النور",
    description: "نزل جبريل عليه السلام بأول آيات: ﴿اقرأ باسم ربك الذي خلق﴾ (العلق: 1–5) في رمضان، وهو ﷺ ابن أربعين سنة تقريبًا." },
  { id: "e10", title: "إسلام خديجة وأبي بكر وعلي وزيد", category: "companions", startYear: 610, approximate: true, location: "مكة",
    description: "أول من آمن: خديجة بنت خويلد، وأبو بكر الصديق، وعلي بن أبي طالب، وزيد بن حارثة رضي الله عنهم." },
  { id: "e11", title: "الدعوة السرية", category: "life", startYear: 610, endYear: 613, approximate: true, location: "مكة",
    description: "نحو ثلاث سنين من الدعوة سرًّا، وكان المسلمون يجتمعون في دار الأرقم بن أبي الأرقم." },
  { id: "e12", title: "الجهر بالدعوة", category: "revelation", startYear: 613, approximate: true, location: "جبل الصفا، مكة",
    description: "نزل قوله تعالى: ﴿وأنذر عشيرتك الأقربين﴾ (الشعراء: 214)، فصعد ﷺ الصفا ونادى بطون قريش." },
  { id: "e13", title: "تعذيب بلال وآل ياسر وغيرهم", category: "companions", startYear: 613, endYear: 615, approximate: true, location: "مكة",
    description: "عُذّب المستضعفون من المسلمين، واستشهدت سمية بنت خياط فكانت أول شهيدة في الإسلام، وأعتق أبو بكر بلالًا." },
  { id: "e14", title: "نزول سورة الروم ببشارة غلبة الروم", category: "revelation", startYear: 614, approximate: true, location: "مكة",
    description: "﴿غُلبت الروم في أدنى الأرض وهم من بعد غلبهم سيغلبون في بضع سنين﴾ (الروم: 2–4)، نزلت بعد هزيمة البيزنطيين أمام الفرس." },
  { id: "e15", title: "الهجرة الأولى إلى الحبشة", category: "companions", startYear: 615, approximate: true, location: "أكسوم، الحبشة",
    description: "هاجرت طائفة من المسلمين، منهم عثمان ورقية، إلى النجاشي الملك العادل، ثم تبعتها هجرة ثانية أكبر، وتكلم جعفر بن أبي طالب بين يدي النجاشي." },
  { id: "e16", title: "إسلام حمزة وعمر رضي الله عنهما", category: "companions", startYear: 616, approximate: true, location: "مكة",
    description: "أسلم رجلان من أشداء قريش، فصار المسلمون يصلّون عند الكعبة جهرًا." },
  { id: "e17", title: "حصار بني هاشم في الشِّعب", category: "life", startYear: 616, endYear: 619, approximate: true, location: "شِعب أبي طالب، مكة",
    description: "قاطعت قريش بني هاشم وبني المطلب، وحُصروا في شعب أبي طالب نحو ثلاث سنين." },
  { id: "e18", title: "عام الحزن: وفاة خديجة وأبي طالب", category: "family", startYear: 619, approximate: true, location: "مكة",
    description: "توفيت زوجه خديجة وعمه وناصره أبو طالب في مدة متقاربة." },
  { id: "e19", title: "رحلته إلى الطائف", category: "life", startYear: 619, approximate: true, location: "الطائف",
    description: "خرج يطلب النصرة من ثقيف فردّوه ورموه بالحجارة، وفي طريق عودته آمن عدّاس النصراني." },
  { id: "e20", title: "زواجه من سودة رضي الله عنها", category: "family", startYear: 620, approximate: true, location: "مكة",
    description: "تزوج سودة بنت زمعة، وكان العقد على عائشة نحو هذا الوقت أيضًا." },
  { id: "e21", title: "الإسراء والمعراج", category: "revelation", startYear: 621, approximate: true, location: "مكة ← بيت المقدس ← السماوات",
    description: "أُسري به ﷺ إلى المسجد الأقصى ثم عُرج به إلى السماوات، وفُرضت الصلوات الخمس." },
  { id: "e22", title: "بيعة العقبة الأولى", category: "diplomacy", startYear: 621, approximate: true, location: "العقبة، منى",
    description: "بايعه اثنا عشر رجلًا من أهل يثرب، وبعث معهم مصعب بن عمير يعلّمهم الإسلام." },
  { id: "e23", title: "بيعة العقبة الثانية", category: "diplomacy", startYear: 622, startMonth: 6, approximate: true, location: "العقبة، منى",
    description: "بايعه نحو ثلاثة وسبعين رجلًا وامرأتان من أهل يثرب على نصرته ﷺ، فمهّدت للهجرة." },
  { id: "e24", title: "الهجرة النبوية إلى المدينة", category: "life", startYear: 622, startMonth: 9, location: "مكة ← المدينة",
    description: "خرج مع أبي بكر فاختبآ في غار ثور، ثم سارا إلى يثرب فصارت مدينة النبي ﷺ. ومنها يُؤرَّخ التقويم الهجري." },
  { id: "e25", title: "بناء مسجد قباء والمسجد النبوي", category: "life", startYear: 622, startMonth: 10, location: "المدينة",
    description: "أُسس أول مسجد في قباء، ثم بُني المسجد النبوي في المدينة." },
  { id: "e26", title: "المؤاخاة بين المهاجرين والأنصار ووثيقة المدينة", category: "diplomacy", startYear: 622, startMonth: 11, approximate: true, location: "المدينة",
    description: "آخى ﷺ بين كل مهاجر وأنصاري، وكُتبت صحيفة تنظم حقوق أهل المدينة وواجباتهم." },
  { id: "e27", title: "تحويل القبلة إلى الكعبة", category: "revelation", startYear: 624, startMonth: 1, approximate: true, location: "المدينة (مسجد القبلتين)",
    description: "﴿فولِّ وجهك شطر المسجد الحرام﴾ (البقرة: 144)، في رجب أو شعبان سنة 2 هـ." },
  { id: "e28", title: "فرض صيام رمضان", category: "revelation", startYear: 624, startMonth: 2, approximate: true, location: "المدينة",
    description: "نزل في شعبان سنة 2 هـ (البقرة: 183–185)، وفُرضت زكاة الفطر كذلك." },
  { id: "e29", title: "غزوة بدر الكبرى", category: "battles", startYear: 624, startMonth: 3, location: "بدر",
    description: "17 رمضان سنة 2 هـ. انتصر نحو 313 من المسلمين على جيش قريش البالغ نحو ألف." },
  { id: "e30", title: "وفاة رقية رضي الله عنها", category: "family", startYear: 624, startMonth: 3, location: "المدينة",
    description: "توفيت ابنته ﷺ زوج عثمان والمسلمون في بدر." },
  { id: "e31", title: "زواج علي وفاطمة رضي الله عنهما", category: "family", startYear: 624, approximate: true, location: "المدينة",
    description: "تزوجت فاطمة الزهراء من علي بن أبي طالب سنة 2 هـ." },
  { id: "e32", title: "غزوة أحد", category: "battles", startYear: 625, startMonth: 3, location: "جبل أحد",
    description: "شوال سنة 3 هـ. ترك الرماة مواقعهم فأصاب المسلمين ما أصابهم، واستشهد حمزة بن عبد المطلب." },
  { id: "e33", title: "مولد الحسن بن علي", category: "family", startYear: 625, approximate: true, location: "المدينة",
    description: "وُلد سبطه الحسن بن علي في رمضان سنة 3 هـ، ووُلد الحسين في العام التالي." },
  { id: "e34", title: "إجلاء بني النضير", category: "battles", startYear: 625, startMonth: 8, approximate: true, location: "المدينة",
    description: "سنة 4 هـ. أُجلوا بعد أن همّوا بقتل النبي ﷺ ونقضوا العهد." },
  { id: "e35", title: "غزوة الخندق (الأحزاب)", category: "battles", startYear: 627, startMonth: 3, endYear: 627, endMonth: 4, location: "المدينة",
    description: "سنة 5 هـ. حُفر الخندق بمشورة سلمان الفارسي، وحاصرت الأحزاب المدينة بنحو عشرة آلاف ثم انصرفوا." },
  { id: "e36", title: "صلح الحديبية", category: "diplomacy", startYear: 628, startMonth: 3, location: "الحديبية",
    description: "ذو القعدة سنة 6 هـ. هدنة عشر سنين مع قريش، سمّتها سورة الفتح ﴿فتحًا مبينًا﴾، وسبقتها بيعة الرضوان." },
  { id: "e37", title: "الرسائل إلى الملوك", category: "diplomacy", startYear: 628, endYear: 629, approximate: true, location: "المدينة",
    description: "بعث كتبه يدعو إلى الإسلام إلى هرقل، وكسرى أبرويز، والنجاشي، والمقوقس عظيم مصر، وغيرهم." },
  { id: "e38", title: "غزوة خيبر", category: "battles", startYear: 628, startMonth: 5, location: "خيبر",
    description: "محرم سنة 7 هـ. فُتحت حصون خيبر، وقدم جعفر ومن معه من الحبشة." },
  { id: "e39", title: "عمرة القضاء", category: "life", startYear: 629, startMonth: 3, location: "مكة",
    description: "ذو القعدة سنة 7 هـ. اعتمر المسلمون وفق شروط صلح الحديبية." },
  { id: "e40", title: "غزوة مؤتة", category: "battles", startYear: 629, startMonth: 9, location: "مؤتة، الشام",
    description: "جمادى الأولى سنة 8 هـ. أول مواجهة مع الروم، استشهد فيها زيد وجعفر وعبد الله بن رواحة، وانحاز خالد بن الوليد بالجيش." },
  { id: "e41", title: "فتح مكة", category: "battles", startYear: 630, startMonth: 1, location: "مكة",
    description: "رمضان سنة 8 هـ. فُتحت مكة دون قتال يُذكر، وأُعلن العفو العام، وحُطّمت الأصنام حول الكعبة." },
  { id: "e42", title: "غزوة حنين وحصار الطائف", category: "battles", startYear: 630, startMonth: 1, endYear: 630, endMonth: 3, location: "حنين والطائف",
    description: "شوال سنة 8 هـ. هُزمت هوازن وثقيف في حنين، ثم حوصرت الطائف." },
  { id: "e43", title: "مولد إبراهيم ابن النبي ﷺ", category: "family", startYear: 630, startMonth: 4, approximate: true, location: "المدينة",
    description: "وُلد ابنه إبراهيم من مارية القبطية." },
  { id: "e44", title: "غزوة تبوك", category: "battles", startYear: 630, startMonth: 10, location: "تبوك",
    description: "رجب سنة 9 هـ. خرج جيش العسرة بنحو ثلاثين ألفًا لملاقاة الروم فلم يلقوا قتالًا." },
  { id: "e45", title: "عام الوفود", category: "diplomacy", startYear: 630, startMonth: 10, endYear: 631, endMonth: 12, approximate: true, location: "المدينة",
    description: "سنة 9–10 هـ. قدمت وفود القبائل من أنحاء الجزيرة العربية إلى المدينة تعلن إسلامها." },
  { id: "e46", title: "وفاة النجاشي", category: "world", startYear: 630, approximate: true, location: "الحبشة",
    description: "صلّى عليه النبي ﷺ صلاة الغائب، وهو أصحمة النجاشي الذي آوى المسلمين." },
  { id: "e47", title: "وفاة إبراهيم وكسوف الشمس", category: "family", startYear: 632, startMonth: 1, location: "المدينة",
    description: "توفي ابنه الرضيع إبراهيم، وكسفت الشمس يومها، فبيّن ﷺ أن الشمس والقمر لا ينكسفان لموت أحد ولا لحياته." },
  { id: "e48", title: "حجة الوداع", category: "life", startYear: 632, startMonth: 3, location: "مكة وعرفة",
    description: "ذو الحجة سنة 10 هـ. حجته الوحيدة، وفيها خطبة الوداع بعرفة." },
  { id: "e49", title: "﴿اليوم أكملت لكم دينكم﴾", category: "revelation", startYear: 632, startMonth: 3, location: "عرفة",
    description: "نزلت آية المائدة (3) يوم عرفة في حجة الوداع." },
  { id: "e50", title: "وفاة النبي محمد ﷺ", category: "life", startYear: 632, startMonth: 6, location: "المدينة",
    description: "ربيع الأول سنة 11 هـ، وهو ابن ثلاث وستين سنة تقريبًا، في حجرة عائشة رضي الله عنها." },
  { id: "e51", title: "بيعة أبي بكر الصديق خليفةً", category: "companions", startYear: 632, startMonth: 6, location: "سقيفة بني ساعدة، المدينة",
    description: "بايع الصحابة أبا بكر الصديق رضي الله عنه." },

  // ---- آل البيت ----
  { id: "f1", title: "مولد زينب", category: "family", startYear: 599, approximate: true, location: "مكة", description: "كبرى بناته ﷺ." },
  { id: "f2", title: "مولد رقية", category: "family", startYear: 601, approximate: true, location: "مكة", description: "" },
  { id: "f3", title: "مولد أم كلثوم", category: "family", startYear: 603, approximate: true, location: "مكة", description: "" },
  { id: "f4", title: "مولد فاطمة", category: "family", startYear: 605, approximate: true, location: "مكة",
    description: "يُذكر عادةً أنه كان قرب إعادة بناء الكعبة، وفي بعض الروايات أنه بعد ذلك." },
  { id: "f5", title: "بناء النبي ﷺ بعائشة", category: "family", startYear: 623, approximate: true, location: "المدينة", description: "" },
  { id: "f6", title: "وفاة زينب", category: "family", startYear: 629, approximate: true, location: "المدينة", description: "" },
  { id: "f7", title: "وفاة أم كلثوم", category: "family", startYear: 630, endYear: 631, approximate: true, location: "المدينة", description: "توفيت سنة 9 هـ." },

  // ---- أحداث العالم ----
  { id: "w1", title: "وفاة كسرى أنوشروان وتولي هرمز الرابع", category: "world", startYear: 579, location: "الإمبراطورية الساسانية", description: "" },
  { id: "w2", title: "أسرة سوي توحّد الصين", category: "world", startYear: 581, endYear: 589, location: "الصين",
    description: "أسس الإمبراطور ون أسرة سوي سنة 581 ووحّد الصين سنة 589." },
  { id: "w3", title: "حكم الإمبراطور موريس للروم", category: "world", startYear: 582, endYear: 602, location: "القسطنطينية", description: "" },
  { id: "w4", title: "حكم كسرى أبرويز لفارس", category: "world", startYear: 590, endYear: 628, location: "المدائن",
    description: "ملك الفرس الذي مزّق كتاب النبي ﷺ، وقد خُلع وقُتل سنة 628." },
  { id: "w5", title: "البابا غريغوري الكبير", category: "world", startYear: 590, endYear: 604, location: "روما", description: "" },
  { id: "w6", title: "بعثة أوغسطين التنصيرية إلى إنجلترا", category: "world", startYear: 597, location: "كنت، إنجلترا", description: "" },
  { id: "w7", title: "الحرب الرومية الفارسية", category: "world", startYear: 602, endYear: 628, location: "الشرق الأدنى",
    description: "آخر الحروب بين القوتين العظميين المجاورتين لجزيرة العرب وأشدها تدميرًا." },
  { id: "w8", title: "دستور الأمير شوتوكو ذو السبع عشرة مادة", category: "world", startYear: 604, location: "اليابان", description: "" },
  { id: "w9", title: "إمبراطورية هارشا في شمال الهند", category: "world", startYear: 606, endYear: 647, location: "قنوج، الهند", description: "" },
  { id: "w10", title: "هرقل إمبراطورًا للروم", category: "world", startYear: 610, startMonth: 10, location: "القسطنطينية",
    description: "تُوّج في العام نفسه الذي بدأ فيه الوحي، وهو الذي بلغه كتاب النبي ﷺ فيما بعد." },
  { id: "w11", title: "الفرس يستولون على بيت المقدس", category: "world", startYear: 614, startMonth: 5, location: "بيت المقدس",
    description: "استولى الساسانيون على بيت المقدس وأخذوا الصليب، وهي هزيمة الروم التي ذكرتها سورة الروم." },
  { id: "w12", title: "قيام أسرة تانغ في الصين", category: "world", startYear: 618, location: "تشانغآن، الصين", description: "" },
  { id: "w13", title: "الفتح الفارسي لمصر", category: "world", startYear: 618, endYear: 621, location: "مصر", description: "" },
  { id: "w14", title: "حصار القسطنطينية", category: "world", startYear: 626, startMonth: 7, location: "القسطنطينية",
    description: "حاصر الآفار والفرس عاصمة الروم فصمدت." },
  { id: "w15", title: "معركة نينوى: انتصار هرقل على الفرس", category: "world", startYear: 627, startMonth: 12, location: "قرب الموصل",
    description: "النصر الحاسم للروم، وفيه تحقق ما بشّرت به سورة الروم." },
  { id: "w16", title: "هرقل يعيد الصليب إلى بيت المقدس", category: "world", startYear: 630, startMonth: 3, location: "بيت المقدس", description: "" },
  { id: "w17", title: "رحلة شوان زانغ إلى الهند", category: "world", startYear: 629, endYear: 645, location: "الصين ← الهند", description: "" }
];
