// Sample data loaded the first time the app opens (or after "Reset to sample data").
// Dates are given in the Common Era (CE). Many dates in the Seerah are approximate
// and scholars differ on some of them — edit freely to match the sources you follow.
//
// Event fields:
//   id, title, category, startYear, startMonth (1-12, optional),
//   endYear / endMonth (optional, for events that span time),
//   approximate (true/false), location, description, sources

window.SEED_CATEGORIES = [
  { id: "life", name: "Prophet's Life", color: "#0f766e" },
  { id: "revelation", name: "Revelation", color: "#b45309" },
  { id: "family", name: "Family", color: "#be185d" },
  { id: "companions", name: "Companions", color: "#4338ca" },
  { id: "battles", name: "Battles & Expeditions", color: "#b91c1c" },
  { id: "diplomacy", name: "Treaties & Diplomacy", color: "#7e22ce" },
  { id: "world", name: "World Events", color: "#475569" }
];

window.SEED_EVENTS = [
  // ---- Prophet's life ----
  { id: "e1", title: "Year of the Elephant & birth of the Prophet ﷺ", category: "life", startYear: 570, startMonth: 4, approximate: true, location: "Mecca",
    description: "Abraha's army from Yemen marches on the Ka'bah with elephants and is turned back. The Prophet Muhammad ﷺ is born in Rabi' al-Awwal of the same year." },
  { id: "e2", title: "Raised among Banu Sa'd with Halimah", category: "life", startYear: 570, endYear: 575, approximate: true, location: "Desert of Banu Sa'd",
    description: "Nursed and raised in the desert by Halimah al-Sa'diyyah, as was the custom of the Quraysh. The incident of the opening of the chest takes place during this time." },
  { id: "e3", title: "Death of his mother Aminah", category: "life", startYear: 576, approximate: true, location: "Al-Abwa'",
    description: "Aminah bint Wahb dies on the way back from Yathrib when he is about six years old. He passes into the care of his grandfather Abd al-Muttalib." },
  { id: "e4", title: "Death of Abd al-Muttalib", category: "life", startYear: 578, approximate: true, location: "Mecca",
    description: "His grandfather dies when he is about eight. His uncle Abu Talib becomes his guardian." },
  { id: "e5", title: "Trade journey to Syria; meeting Bahira", category: "life", startYear: 582, approximate: true, location: "Bosra, Syria",
    description: "Travels with Abu Talib's caravan at about twelve years old. The monk Bahira recognizes signs of prophethood in him." },
  { id: "e6", title: "Hilf al-Fudul (Pact of the Virtuous)", category: "diplomacy", startYear: 590, approximate: true, location: "Mecca",
    description: "A pact among clans of Quraysh to defend anyone wronged in Mecca. He later said he would still answer such a call in Islam." },
  { id: "e7", title: "Marriage to Khadijah", category: "family", startYear: 595, approximate: true, location: "Mecca",
    description: "Marries Khadijah bint Khuwaylid, a respected merchant, after leading her caravan to Syria. He is about 25." },
  { id: "e8", title: "Rebuilding of the Ka'bah", category: "life", startYear: 605, approximate: true, location: "Mecca",
    description: "Quraysh rebuild the Ka'bah. He settles the dispute over who should replace the Black Stone by placing it on a cloak carried by every clan." },
  { id: "e9", title: "First revelation in the Cave of Hira", category: "revelation", startYear: 610, startMonth: 8, approximate: true, location: "Cave of Hira, Jabal al-Nur",
    description: "Jibril brings the first verses: \"Read in the name of your Lord who created\" (Al-'Alaq 96:1–5), in Ramadan. He is about 40." },
  { id: "e10", title: "Khadijah, Abu Bakr, Ali and Zayd accept Islam", category: "companions", startYear: 610, approximate: true, location: "Mecca",
    description: "The first believers: Khadijah, Abu Bakr al-Siddiq, Ali ibn Abi Talib and Zayd ibn Harithah." },
  { id: "e11", title: "Secret call to Islam", category: "life", startYear: 610, endYear: 613, approximate: true, location: "Mecca",
    description: "About three years of quiet invitation, with believers meeting at Dar al-Arqam." },
  { id: "e12", title: "Public call begins", category: "revelation", startYear: 613, approximate: true, location: "Mount Safa, Mecca",
    description: "\"And warn your nearest kinsmen\" (Al-Shu'ara 26:214). He calls the clans of Quraysh from Mount Safa." },
  { id: "e13", title: "Persecution of Bilal, Ammar's family and others", category: "companions", startYear: 613, endYear: 615, approximate: true, location: "Mecca",
    description: "Weaker Muslims are tortured. Sumayyah bint Khayyat becomes the first martyr of Islam. Abu Bakr frees Bilal." },
  { id: "e14", title: "Surat al-Rum foretells Roman victory", category: "revelation", startYear: 614, approximate: true, location: "Mecca",
    description: "\"The Romans have been defeated in the nearest land, but after their defeat they will be victorious within a few years\" (30:2–4), revealed after the Persians defeated the Byzantines." },
  { id: "e15", title: "First migration to Abyssinia", category: "companions", startYear: 615, approximate: true, location: "Aksum, Abyssinia",
    description: "A group of Muslims, among them Uthman and Ruqayyah, migrate to the just Christian king, the Negus (al-Najashi). A larger group follows soon after, and Ja'far ibn Abi Talib speaks before the Negus." },
  { id: "e16", title: "Hamzah and Umar accept Islam", category: "companions", startYear: 616, approximate: true, location: "Mecca",
    description: "Two strong men of Quraysh accept Islam, and the Muslims begin to pray openly at the Ka'bah." },
  { id: "e17", title: "Boycott of Banu Hashim", category: "life", startYear: 616, endYear: 619, approximate: true, location: "Shi'b Abi Talib, Mecca",
    description: "Quraysh boycott Banu Hashim and Banu al-Muttalib, who are confined to the valley of Abu Talib for about three years." },
  { id: "e18", title: "Year of Sorrow: deaths of Khadijah and Abu Talib", category: "family", startYear: 619, approximate: true, location: "Mecca",
    description: "His wife Khadijah and his uncle and protector Abu Talib die within a short time of each other." },
  { id: "e19", title: "Journey to Ta'if", category: "life", startYear: 619, approximate: true, location: "Ta'if",
    description: "He seeks support from Thaqif in Ta'if and is rejected and stoned. On the way back, Addas the Christian slave believes." },
  { id: "e20", title: "Marriage to Sawdah", category: "family", startYear: 620, approximate: true, location: "Mecca",
    description: "Marries Sawdah bint Zam'ah. His marriage contract with Aishah is also made around this time." },
  { id: "e21", title: "Al-Isra' wal-Mi'raj", category: "revelation", startYear: 621, approximate: true, location: "Mecca → Jerusalem → the heavens",
    description: "The Night Journey to al-Masjid al-Aqsa and the Ascension. The five daily prayers are made obligatory." },
  { id: "e22", title: "First Pledge of Aqabah", category: "diplomacy", startYear: 621, approximate: true, location: "Aqabah, Mina",
    description: "Twelve men from Yathrib pledge allegiance. Mus'ab ibn Umayr is sent with them to teach Islam." },
  { id: "e23", title: "Second Pledge of Aqabah", category: "diplomacy", startYear: 622, startMonth: 6, approximate: true, location: "Aqabah, Mina",
    description: "About seventy-three men and two women from Yathrib pledge to protect the Prophet ﷺ, which opens the way for the Hijrah." },
  { id: "e24", title: "The Hijrah to Madinah", category: "life", startYear: 622, startMonth: 9, location: "Mecca → Madinah",
    description: "With Abu Bakr he hides in the Cave of Thawr, then travels to Yathrib, which becomes Madinat al-Nabi. The Islamic calendar later counts its years from this one." },
  { id: "e25", title: "Masjid Quba and al-Masjid al-Nabawi built", category: "life", startYear: 622, startMonth: 10, location: "Madinah",
    description: "The first mosque is founded at Quba, then the Prophet's Mosque in Madinah." },
  { id: "e26", title: "Brotherhood of Muhajirun and Ansar; Charter of Madinah", category: "diplomacy", startYear: 622, startMonth: 11, approximate: true, location: "Madinah",
    description: "Each emigrant is paired with a helper. A written charter sets out the rights and duties of the communities of Madinah." },
  { id: "e27", title: "Change of the Qiblah to the Ka'bah", category: "revelation", startYear: 624, startMonth: 1, approximate: true, location: "Madinah (Masjid al-Qiblatayn)",
    description: "\"So turn your face toward al-Masjid al-Haram\" (Al-Baqarah 2:144), in Rajab or Sha'ban, 2 AH." },
  { id: "e28", title: "Fasting of Ramadan made obligatory", category: "revelation", startYear: 624, startMonth: 2, approximate: true, location: "Madinah",
    description: "Revealed in Sha'ban, 2 AH (Al-Baqarah 2:183–185). Zakat al-Fitr is also prescribed." },
  { id: "e29", title: "Battle of Badr", category: "battles", startYear: 624, startMonth: 3, location: "Badr",
    description: "17 Ramadan, 2 AH. About 313 Muslims defeat a Qurayshi army of about 1,000." },
  { id: "e30", title: "Death of Ruqayyah", category: "family", startYear: 624, startMonth: 3, location: "Madinah",
    description: "The Prophet's daughter, wife of Uthman, dies while the Muslims are at Badr." },
  { id: "e31", title: "Marriage of Ali and Fatimah", category: "family", startYear: 624, approximate: true, location: "Madinah",
    description: "Fatimah al-Zahra marries Ali ibn Abi Talib in 2 AH." },
  { id: "e32", title: "Battle of Uhud", category: "battles", startYear: 625, startMonth: 3, location: "Mount Uhud",
    description: "Shawwal, 3 AH. The archers leave their position and the Muslims suffer losses. Hamzah ibn Abd al-Muttalib is martyred." },
  { id: "e33", title: "Birth of al-Hasan", category: "family", startYear: 625, approximate: true, location: "Madinah",
    description: "His grandson al-Hasan ibn Ali is born in Ramadan, 3 AH. Al-Husayn follows the next year." },
  { id: "e34", title: "Expulsion of Banu al-Nadir", category: "battles", startYear: 625, startMonth: 8, approximate: true, location: "Madinah",
    description: "4 AH. Expelled after plotting to kill the Prophet ﷺ, in breach of their treaty." },
  { id: "e35", title: "Battle of the Trench (al-Khandaq)", category: "battles", startYear: 627, startMonth: 3, endYear: 627, endMonth: 4, location: "Madinah",
    description: "5 AH. On Salman al-Farisi's advice a trench is dug, and an allied army of about 10,000 besieges Madinah and then withdraws." },
  { id: "e36", title: "Treaty of al-Hudaybiyah", category: "diplomacy", startYear: 628, startMonth: 3, location: "Al-Hudaybiyah",
    description: "Dhu al-Qa'dah, 6 AH. A ten-year truce with Quraysh, which Surat al-Fath calls \"a clear victory\". The Pledge of Ridwan comes before it." },
  { id: "e37", title: "Letters to the rulers", category: "diplomacy", startYear: 628, endYear: 629, approximate: true, location: "Madinah",
    description: "Letters inviting to Islam are sent to Heraclius, Khosrow II, the Negus, al-Muqawqis of Egypt and others." },
  { id: "e38", title: "Battle of Khaybar", category: "battles", startYear: 628, startMonth: 5, location: "Khaybar",
    description: "Muharram, 7 AH. The fortresses of Khaybar are taken. Ja'far and the emigrants return from Abyssinia." },
  { id: "e39", title: "'Umrat al-Qada' (the make-up Umrah)", category: "life", startYear: 629, startMonth: 3, location: "Mecca",
    description: "Dhu al-Qa'dah, 7 AH. The Muslims perform Umrah under the terms of Hudaybiyah." },
  { id: "e40", title: "Battle of Mu'tah", category: "battles", startYear: 629, startMonth: 9, location: "Mu'tah, Syria",
    description: "Jumada al-Ula, 8 AH. The first clash with Byzantine forces. Zayd, Ja'far and Abdullah ibn Rawahah are martyred, and Khalid ibn al-Walid withdraws the army." },
  { id: "e41", title: "Conquest of Mecca", category: "battles", startYear: 630, startMonth: 1, location: "Mecca",
    description: "Ramadan, 8 AH. Mecca opens almost without fighting, a general amnesty is declared and the idols of the Ka'bah are destroyed." },
  { id: "e42", title: "Battle of Hunayn and siege of Ta'if", category: "battles", startYear: 630, startMonth: 1, endYear: 630, endMonth: 3, location: "Hunayn & Ta'if",
    description: "Shawwal, 8 AH. Hawazin and Thaqif are defeated at Hunayn, then Ta'if is besieged." },
  { id: "e43", title: "Birth of Ibrahim", category: "family", startYear: 630, startMonth: 4, approximate: true, location: "Madinah",
    description: "His son Ibrahim is born to Mariyah al-Qibtiyyah." },
  { id: "e44", title: "Expedition of Tabuk", category: "battles", startYear: 630, startMonth: 10, location: "Tabuk",
    description: "Rajab, 9 AH. An army of about 30,000 marches against the Byzantines, who do not appear." },
  { id: "e45", title: "The Year of Delegations", category: "diplomacy", startYear: 630, startMonth: 10, endYear: 631, endMonth: 12, approximate: true, location: "Madinah",
    description: "9–10 AH. Delegations from tribes across Arabia come to Madinah to accept Islam." },
  { id: "e46", title: "Death of the Negus al-Najashi", category: "world", startYear: 630, approximate: true, location: "Abyssinia",
    description: "The Prophet ﷺ leads the funeral prayer in absentia for Ashamah, the Negus who sheltered the Muslims." },
  { id: "e47", title: "Death of Ibrahim; solar eclipse", category: "family", startYear: 632, startMonth: 1, location: "Madinah",
    description: "His infant son Ibrahim dies. An eclipse happens the same day, and he teaches that eclipses do not happen for anyone's death or birth." },
  { id: "e48", title: "Farewell Pilgrimage", category: "life", startYear: 632, startMonth: 3, location: "Mecca & Arafah",
    description: "Dhu al-Hijjah, 10 AH. His only Hajj and the Farewell Sermon at Arafah." },
  { id: "e49", title: "\"Today I have perfected your religion\"", category: "revelation", startYear: 632, startMonth: 3, location: "Arafah",
    description: "Al-Ma'idah 5:3 is revealed on the Day of Arafah during the Farewell Pilgrimage." },
  { id: "e50", title: "Death of the Prophet Muhammad ﷺ", category: "life", startYear: 632, startMonth: 6, location: "Madinah",
    description: "Rabi' al-Awwal, 11 AH, at about 63 years old, in the room of Aishah." },
  { id: "e51", title: "Abu Bakr chosen as the first Caliph", category: "companions", startYear: 632, startMonth: 6, location: "Saqifah of Banu Sa'idah, Madinah",
    description: "The companions give the pledge to Abu Bakr al-Siddiq." },

  // ---- Family ----
  { id: "f1", title: "Birth of Zaynab", category: "family", startYear: 599, approximate: true, location: "Mecca", description: "His eldest daughter." },
  { id: "f2", title: "Birth of Ruqayyah", category: "family", startYear: 601, approximate: true, location: "Mecca", description: "" },
  { id: "f3", title: "Birth of Umm Kulthum", category: "family", startYear: 603, approximate: true, location: "Mecca", description: "" },
  { id: "f4", title: "Birth of Fatimah", category: "family", startYear: 605, approximate: true, location: "Mecca",
    description: "Commonly placed around the rebuilding of the Ka'bah. Some reports place her birth later." },
  { id: "f5", title: "Aishah joins the Prophet's household", category: "family", startYear: 623, approximate: true, location: "Madinah", description: "" },
  { id: "f6", title: "Death of Zaynab", category: "family", startYear: 629, approximate: true, location: "Madinah", description: "" },
  { id: "f7", title: "Death of Umm Kulthum", category: "family", startYear: 630, endYear: 631, approximate: true, location: "Madinah", description: "Died in 9 AH." },

  // ---- World events ----
  { id: "w1", title: "Khosrow I dies; Hormizd IV rules Persia", category: "world", startYear: 579, location: "Sasanian Empire", description: "" },
  { id: "w2", title: "Sui dynasty reunifies China", category: "world", startYear: 581, endYear: 589, location: "China",
    description: "Emperor Wen founds the Sui dynasty in 581 and reunifies China in 589." },
  { id: "w3", title: "Emperor Maurice rules Byzantium", category: "world", startYear: 582, endYear: 602, location: "Constantinople", description: "" },
  { id: "w4", title: "Khosrow II reigns in Persia", category: "world", startYear: 590, endYear: 628, location: "Ctesiphon",
    description: "The Sasanian king who later tore up the Prophet's letter. He was deposed and killed in 628." },
  { id: "w5", title: "Pope Gregory the Great", category: "world", startYear: 590, endYear: 604, location: "Rome", description: "" },
  { id: "w6", title: "Augustine's mission to England", category: "world", startYear: 597, location: "Kent, England", description: "" },
  { id: "w7", title: "Byzantine–Sasanian War", category: "world", startYear: 602, endYear: 628, location: "Near East",
    description: "The last and most destructive war between the two superpowers that bordered Arabia." },
  { id: "w8", title: "Shotoku's Seventeen-Article Constitution", category: "world", startYear: 604, location: "Japan", description: "" },
  { id: "w9", title: "Harsha's empire in northern India", category: "world", startYear: 606, endYear: 647, location: "Kannauj, India", description: "" },
  { id: "w10", title: "Heraclius becomes Byzantine emperor", category: "world", startYear: 610, startMonth: 10, location: "Constantinople",
    description: "Crowned in the same year as the first revelation. He later received the Prophet's letter." },
  { id: "w11", title: "Persians capture Jerusalem", category: "world", startYear: 614, startMonth: 5, location: "Jerusalem",
    description: "The Sasanians take Jerusalem and carry off the True Cross, the Roman defeat referred to in Surat al-Rum." },
  { id: "w12", title: "Tang dynasty founded in China", category: "world", startYear: 618, location: "Chang'an, China", description: "" },
  { id: "w13", title: "Persian conquest of Egypt", category: "world", startYear: 618, endYear: 621, location: "Egypt", description: "" },
  { id: "w14", title: "Siege of Constantinople", category: "world", startYear: 626, startMonth: 7, location: "Constantinople",
    description: "Avars and Persians besiege the Byzantine capital, which holds out." },
  { id: "w15", title: "Battle of Nineveh: Heraclius defeats Persia", category: "world", startYear: 627, startMonth: 12, location: "Near Mosul",
    description: "The decisive Roman victory, fulfilling the prophecy of Surat al-Rum." },
  { id: "w16", title: "Heraclius returns the True Cross to Jerusalem", category: "world", startYear: 630, startMonth: 3, location: "Jerusalem", description: "" },
  { id: "w17", title: "Xuanzang's pilgrimage to India", category: "world", startYear: 629, endYear: 645, location: "China → India", description: "" }
];
